DROP TABLE IF EXISTS post2;
CREATE TABLE IF NOT EXISTS post2(
    id INT AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(10) NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    secret INT NOT NULL DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
)